FROM registry.gitlab.com/cianwilson/thermocodegen:jammy-merge-upgrades

USER tcg
WORKDIR $TCG_HOME
# Clone the eclogitization repo
RUN git clone https://gitlab.com/mitchellmcm27/eclogite-tcg.git

USER root

# Install dependencies
RUN pip install --upgrade\
        jill==0.11.5\
        numpy==1.24.4\
        scipy==1.10.1\
        pandas==2.0.3\
        numexpr==2.7.3\
        matplotlib==3.7.5\
        sympy==1.12\
    && jill install '"1.10"' --upstream Official --confirm\
    && julia -e 'using Pkg; Pkg.add(["JSON","Plots"]); Pkg.add(name="StatGeochemBase",version="0.6.14");'

RUN cd eclogite-tcg\
    # Set permissions
    && chgrp adm -R .\
    && chmod g+w+x -R .\
    # Generate and build reactions
    && cd tcg_slb_database\
    && scripts/generate_reactions_eclogite -v slb21\
    && scripts/build_reactions database/reactions/eclogitization_2024_slb21_rx.rxml\
    # Install Perple_x v7.0.10
    && mkdir ~/resources\
    && git clone -n https://github.com/jadconnolly/Perple_X.git ~/resources/perplex-stable\
    && cd ~/resources/perplex-stable\
    && git checkout 1aeec2f4f5d31762ecc8a5abbcb6338046406306\
    # && git checkout v7.1.9\
    && cd src\
    && make -j${nproc}\
    # copy files to the directory required by the Perple_X Julia interface
    && cd ~/resources/perplex-stable\
    && cp src/* .\
    && cp -r datafiles/* .\
    && cp optionfiles/* .

# override the perplex-datafiles to use the ones directly from perplex
#RUN mkdir ~/perplex-datafiles\
#    && cp -r ~/resources/perplex-stable/datafiles/* /root/perplex-datafiles\
#    && cp -r ~/resources/perplex-stable/optionfiles/* /root/perplex-datafiles\
#    && mkdir ~/.julia\
#    && mkdir ~/.julia/artifacts\
#    && echo '[df4de05a-b714-11e8-3c2a-c30fb13e804c]\nperplex-datafiles = "/root"' >> ~/.julia/artifacts/Overrides.toml\
#    && julia -e 'using Pkg; Pkg.add("JSON"); Pkg.add(name="StatGeochem", version="0.8.2");'

WORKDIR $TCG_HOME/eclogite-tcg

USER root