FROM registry.gitlab.com/enki-portal/thermocodegen:focal

# Prepare working directory
ENV EC_DIR /home/tcg/shared/eclogite-tcg
RUN mkdir $EC_DIR
WORKDIR $EC_DIR

# copy only what is necessary to build reactions
# (better cache performance)
COPY tcg_slb tcg_slb
RUN cd tcg_slb\
    && chmod +x -R .\
    && scripts/generate_reactions_eclogite -v 21\
    && scripts/build_reactions database/reactions/eclogitization_2024_stx21_rx.rxml

# copy everything else
COPY . .
RUN chgrp adm -R .\
    && chmod g+w+x -R .

# Install Julia and the JSON package
RUN pip install jill -U\
    && pip install --upgrade matplotlib julia
ENV PATH="/usr/local/bin:${PATH}"
RUN jill install 1.9 --upstream Official --confirm
RUN julia -e 'using Pkg; Pkg.add(["JSON"]);'

# The Perple_X Julia interface requires all files to be in a specific directory
RUN mkdir ~/resources

# Install Perple_x v7.0.10
RUN git clone -n https://github.com/jadconnolly/Perple_X.git ~/resources/perplex-stable \
    && cd ~/resources/perplex-stable \
    && git checkout 1aeec2f4f5d31762ecc8a5abbcb6338046406306 \
    && cd src \
    && make -j${nproc}

# Copy files
RUN cd ~/resources/perplex-stable\
    && cp src/* .\
    && cp -r datafiles/* .\
    && cp optionfiles/* .

# R Stuff
#RUN apt-get install -y r-base
#RUN R -e "install.packages(c('tidyverse', 'ggthemes', 'colorspace', 'latex2exp', 'latex2exp'))"

WORKDIR $EC_DIR