#!/usr/bin/env python3

import os,sys
import pandas as pd
import ast
import numpy as np
import sympy as sym
from collections import OrderedDict
from thermocodegen.coder import coder
from reactions_claude_7 import reactions_claude

sys.path.append(os.path.join(os.path.dirname(__file__), os.path.pardir, 'python'))
from tcg_slb.reactions import SLBReactions

reference = 'generate_reactions_eclogite'

os.chdir(os.path.abspath(os.path.dirname(__file__)))

def generate_reactions(outdir,version):
    
    an = ['Feldspar', 'Anorthite']    
    ab = ['Feldspar', 'Albite']
    fs = ['Orthopyroxene', 'Ferrosilite']
    oEn = ['Orthopyroxene', 'Enstatite']
    mgts = ['Orthopyroxene', 'MgTschermaks']
    oDi = ['Orthopyroxene', 'OrthoDiopside']
    hed = ['Clinopyroxene', 'Hedenbergite']
    di = ['Clinopyroxene', 'Diopside']
    jd = ['Clinopyroxene', 'Jadeite']
    cats = ['Clinopyroxene', 'CaTschermaks']
    cEn = ['Clinopyroxene', 'Clinoenstatite']
    alm = ['Garnet', 'Almandine']
    pyp = ['Garnet', 'Pyrope']
    gs = ['Garnet', 'Grossular']
    qz = ['Quartz', 'Quartz']
    ky = ['Kyanite', 'Kyanite']
    mgsp = ['Spinel', 'MgSpinel']
    herc = ['Spinel', 'Hercynite']
    fo = ['Olivine', 'Forsterite']
    fa = ['Olivine', 'Fayalite']


    phases=[
        'Clinopyroxene',
        'Orthopyroxene',
        'Quartz',
        'Feldspar',
        'Garnet',
        'Kyanite',
    ]

    phases_mafic=[
        'Clinopyroxene',
        'Orthopyroxene',
        'Quartz',
        'Feldspar',
        'Garnet',
        'Kyanite',
        'Spinel',
        'Olivine'
    ]

    reactions_2024 = [
        ([hed, oEn],[di, fs]), # Fe-Mg exchange, Cpx-Opx
        ([pyp, fs],[alm, oEn]), # Fe-Mg exchange, Grt-Opx
        ([pyp, hed], [alm, di]), # Ellis & Green 1979 (1), #Fe-Mg exchange, Grt-Cpx
        ([oEn],[cEn]),
        ([oDi],[di]),
        ([cats, pyp], [gs, mgts]), # cation exchange with Tschermaks
        ([an], [cats, qz]), # Paria et al (paragraph 2, cites Herzberg 1978), GR67b
        ([an, oEn], [di, mgts, qz]), # Green & Ringwood 1967 (a) - GR67a
        ([an, oEn], [pyp, di, qz]),  # GR67c, Paria et al (B)
        ([an, oEn], [pyp, gs, qz]), # GR67d
        ([an, fs], [alm, hed, qz]), # Paria et al (A), GR67c
        ([an, fs], [alm, gs, qz]),  # GR67d
        ([oEn, mgts], [pyp]), # Paria et al (paragraph 2, cites RWood 1974), GR67e, Wood & Banno 1973 (1)
        ([oEn, cats], [gs, pyp]), # GR67f
        ([ab], [jd, qz]), # Paria et al (paragraph 2, Reinsch 1977 cited in Newton 1983), GR67g
        ([gs, pyp, qz], [di, ky]),
        ([gs, alm, qz], [hed, ky]),
        ([pyp, qz], [cEn, ky]),
        ([gs, ky], [cats, qz]),
        ([an], [ky, gs, qz]),  # Koziol et al 1988 (paragraph 1), GR67o
        ([fs, mgts], [pyp, alm]), 
        ([fs, cats], [gs, pyp, alm]),  
        ([an, pyp], [mgts, gs, qz]), # swapped pyp and mgts because it gets swapped by TCG
        ([di, an], [gs, pyp, qz]), 
        ([hed, an], [gs, alm, qz]),
        #([cats, an], [gs, qz]), # removed because this reduces to an = cats + qtz
        ([an, cEn], [gs, pyp, qz])
    ]

    reactions_abdullaziz = [
        ([hed, oEn],[di, fs]), # Fe-Mg exchange, Cpx-Opx
        ([pyp, fs],[alm, oEn]), # Fe-Mg exchange, Grt-Opx
        ([pyp, hed], [alm, di]), # Ellis & Green 1979 (1), #Fe-Mg exchange, Grt-Cpx
        
        #The rest of the Cations: -Abdulaziz
        ([oEn, fa], [fs, fo]),
        ([oEn, herc], [fs, mgsp]),
        ([pyp, herc], [alm, mgsp]),
        ([fo, herc], [fa, mgsp]),
        ([fo, alm], [fa, pyp]),
        ([fo, hed], [fa, di]),
        ([mgsp, hed], [herc, di]),
        
        ([oEn],[cEn]),
        ([oDi],[di]),
        ([cats, pyp], [gs, mgts]), # cation exchange with Tschermaks
        ([an], [cats, qz]), # Paria et al (paragraph 2, cites Herzberg 1978), GR67b
        ([an, oEn], [di, mgts, qz]), # Green & Ringwood 1967 (a) - GR67a
        ([an, oEn], [pyp, di, qz]),  # GR67c, Paria et al (B)
        ([an, oEn], [pyp, gs, qz]), # GR67d
        ([an, fs], [alm, hed, qz]), # Paria et al (A), GR67c
        ([an, fs], [alm, gs, qz]),  # GR67d
        ([oEn, mgts], [pyp]), # Paria et al (paragraph 2, cites RWood 1974), GR67e, Wood & Banno 1973 (1)
        ([oEn, cats], [gs, pyp]), # GR67f
        ([ab], [jd, qz]), # Paria et al (paragraph 2, Reinsch 1977 cited in Newton 1983), GR67g
        ([gs, pyp, qz], [di, ky]),
        ([gs, alm, qz], [hed, ky]),
        ([pyp, qz], [cEn, ky]),
        ([gs, ky], [cats, qz]),
        ([an], [ky, gs, qz]),  # Koziol et al 1988 (paragraph 1), GR67o
        ([fs, mgts], [pyp, alm]), 
        ([fs, cats], [gs, pyp, alm]),  
        ([an, pyp], [mgts, gs, qz]), # swapped pyp and mgts because it gets swapped by TCG
        ([di, an], [gs, pyp, qz]), 
        ([hed, an], [gs, alm, qz]),
        #([cats, an], [gs, qz]), # removed because this reduces to an = cats + qtz
        ([an, cEn], [gs, pyp, qz]),

        # added based on whiteboard discussion
        ([mgsp, qz], [oEn, ky]), #
        ([herc, qz], [fs, ky]), #
        #20/9/2024 Added at lab
        ([di,ky], [an, qz, fo]),
        ([hed,ky], [an, qz, fa]),

        # FROM THIS POINT THERE WERE NO CHANGES TO THE GRAPH
        #Added on 24/9/2024 Might need to check their balancing. Phases graph doesn't look any different after running
        ([fo, qz], [oEn]),
        ([fa, qz], [fs]),

        ([qz,ky,fo], [pyp]),
        ([qz,ky,fa], [alm]),

        #Added on 25/9/2024 during meeting

        # NOTE 1: A valid solution is if there is 0 quartz, anorthite, or cats
        # this is not good, so the reaction must be simplified
        # cats + alm + qz = fa + fs + an + ky

        # this is the Ca-bearing part of the reaction
        # ([cats,qz],[an]), # but we already have this above

        # This is the Fe-bearing part, which works
        ([alm], [fa, fs, ky]),
        
        # Do the same thing for this reaction... cats + pyp + qz = fo + oEn, an, ky]),

        # leaving the Mg-bearing part
        ([pyp], [fo, oEn, ky]),

        # NOTE 2: A solution to this rxn is when ky = fs = qz = 0 (not good)
        #([gs, alm, ky, qz], [fa, fs, an]),

        # but it simplifies to...
        ([gs, alm], [fa, an]),

        # Similarly for Mg
        #([gs, pyp, ky, qz], [fo, oEn, an])
        ([gs, pyp], [fo, an]),

        # added 10-2-2024
        # gt + cpx -> spinel + opx ?
        ([pyp], [mgsp, oEn, qz]),
        ([alm], [herc, fs, qz]),
        #([namj, jd, ky], [mgsp, ab]),
        
        # added 8 - 20 - 2024
        #([mgmj], [cEn]),
        #([mgmj], [oEn])

        ##### Mitchell 10-16-2024
        ([di, ky], [mgsp, an, qz]),
        ([hed, ky], [herc, an, qz]),

        # MacGregor 1970, breaks down into 2 separate reactions each for Mg and Fe
        # mgsp/herc + oEn/fs + di/hed = fo/fa + gs + pyp/alm
        ## equation (1)
        ([mgsp, oEn], [pyp, fo]),
        ([herc, fs], [alm, fa]),
        ## equation (1) but with anorthite and no olivine
        ([mgsp, oEn, an], [gs, pyp]),
        ([herc, fs, an], [gs, alm]),
        ([mgsp, fs, an], [gs, alm, pyp]),
        ([herc, oEn, an], [gs, alm, pyp]),

        ## equation (2)
        ([mgsp, di], [fo, pyp, gs]),
        ([herc, hed] ,[fa, alm, gs]),
        ## equation (2) but with anorthite and no olivine
        ([mgsp, di, an], [gs, pyp]),#?
        ([herc, hed, an], [gs, alm]),#?
        ([mgsp, di, an], [gs, oEn]),
        ([herc, hed, an], [gs, fs]),
        
        # mgsp + opx + fsp = cpx + gt
        # involving anorthite
        ([mgsp, oEn, an], [di, pyp]),
        ([herc, fs, an], [hed, alm]),
        ([mgsp, fs, an], [di, alm]),
        ([herc, oEn, an], [hed, pyp]),

        # involving albite
        ([mgsp, oEn, ab], [jd, pyp]),
        ([herc, fs, ab], [jd, alm]),
        ([herc, oEn, ab], [jd, alm, pyp]),
        ([mgsp, fs, ab], [jd, alm, pyp]),

        # cpx + opx (+mgsp) (+qz) = plg + ol
        # opx, cpx, mgsp
        ([oEn, di, mgsp], [an, fo]),
        ([oEn, di, herc], [an, fo, fa]),
        ([oEn, hed, mgsp], [an, fo, fa]),
        ([oEn, hed, herc], [an, fo, fa]),

        #opx, cpx, mgsp
        ([oEn, jd], [ab, fo]),
        ([fs, jd], [ab, fa]),
        #([jd, oEn, fs], [ab, fa, fo]),

        # opx, cpx, mgsp
        ([fs, hed, herc], [an, fa]),
        ([fs, hed, mgsp], [an, fa, fo]),
        ([fs, di, mgsp], [an, fa, fo]),
        ([fs, di, herc], [an, fa, fo]),

        # opx, opx, mgsp
        ([oEn, fs, mgsp], [an, fo, fa]),
        ([oEn, fs, herc], [an, fo, fa]),
        ([di, hed, mgsp], [an, fo, fa]),
        ([di, hed, herc], [an, fo, fa]),

        # cpx, mgsp, qz
        ([di, mgsp, qz], [an, fo]),
        ([hed, herc, qz], [an, fa]),
        ([di, herc, qz], [an, fo, fa]),
        ([hed, mgsp, qz], [an, fo, fa]),
        #^^^^^^ Mitchell 10-16-2024 

        # vvvvvvvv Whiteboard etc. 10-30-2024
        # Trying 
        # ([mgts],[mgsp, qz]), # tried, did not help
        # ([oEn, mgsp], [mgts, fo]), # tried, did not help
        # ([fs, mgsp], [mgts, fa]), # didn't try
        ([mgts, di],[cats, oEn]), # This helps!
        # ([mgts, gs],[pyp, an]) # tried, did not help
        # ([mgts, hed], [cats, fs, pyp]) # tried, did not help
        ([pyp, ab, di], [oEn, jd, an]), # This helps
        ([alm, ab, hed], [fs, jd, an]), # This helps
        # ^^^^^^^^ Whiteboard etc. 10-30-2024
    ]

    reactions_claude_1 = [
        ([cEn], [oEn]),
        ([di], [oDi]),
        ([an], [qz, cats]),
        ([ab], [qz, jd]),
        ([oEn], [qz, fo]),
        ([fs], [qz, fa]),
        ([mgts], [qz, mgsp]),
        ([cEn], [qz, fo]),
        ([pyp], [oEn, mgts]),
        ([pyp], [mgts, cEn]),
        ([ky, oEn], [qz, pyp]),
        ([ky, oEn], [qz, mgsp]),
        ([ky, fs], [qz, alm]),
        ([ky, fs], [qz, herc]),
        ([ky, cEn], [qz, pyp]),
        ([ky, cEn], [qz, mgsp]),
        ([pyp], [qz, oEn, mgsp]),
        ([alm], [qz, fs, herc]),
        ([pyp], [qz, mgts, fo]),
        ([pyp], [qz, cEn, mgsp]),
        ([mgts], [ky, oEn, mgsp]),
        ([pyp], [ky, oEn, mgsp]),
        ([alm], [ky, fs, herc]),
        ([mgts], [ky, cEn, mgsp]),
        ([mgts], [ky, pyp, mgsp]),
        ([pyp], [ky, cEn, mgsp]),
        ([pyp, mgsp], [ky, fo]),
        ([alm, herc], [ky, fa]),
        ([ab, cats], [an, jd]),
        ([oEn, cats], [an, fo]),
        ([fs, cats], [an, fa]),
        ([oDi, mgts], [an, fo]),
        ([mgts, di], [an, fo]),
        ([mgts, cats], [an, mgsp]),
        ([cEn, cats], [an, fo]),
        ([pyp, gs], [an, fo]),
        ([gs, alm], [an, fa]),
        ([oEn, jd], [ab, fo]),
        ([fs, jd], [ab, fa]),
        ([mgts, jd], [ab, mgsp]),
        ([cEn, jd], [ab, fo]),
        ([fs, pyp], [oEn, alm]),
        ([fs, fo], [oEn, fa]),
        ([oDi, mgts], [oEn, cats]),
        ([mgts, di], [oEn, cats]),
        ([mgts, fo], [oEn, mgsp]),
        ([pyp, gs], [oEn, cats]),
        ([pyp, alm], [fs, mgts]),
        ([mgts, fa], [fs, mgsp]),
        ([cEn, alm], [fs, pyp]),
        ([cEn, fa], [fs, fo]),
        ([gs, alm], [fs, cats]),
        ([cEn, cats], [oDi, mgts]),
        ([pyp, gs], [oDi, mgts]),
        ([hed, mgsp], [oDi, herc]),
        ([pyp, gs], [oDi, cats]),
        ([cats, fo], [oDi, mgsp]),
        ([cEn, cats], [mgts, di]),
        ([pyp, gs], [mgts, di]),
        ([cEn, mgsp], [mgts, fo]),
        ([hed, mgsp], [di, herc]),
        ([pyp, gs], [di, cats]),
        ([cats, fo], [di, mgsp]),
        ([gs, alm], [hed, cats]),
        ([cats, fa], [hed, herc]),
        ([pyp, gs], [cEn, cats]),
        ([alm, fo], [pyp, fa]),
        ([ky, oDi], [qz, an, mgts]),
        ([ky, oDi], [qz, an, pyp]),
        ([ky, di], [qz, an, mgts]),
        ([ky, di], [qz, an, pyp]),
        ([ky, hed], [qz, an, alm]),
        ([ky, oDi], [qz, oEn, cats]),
        ([ky, di], [qz, oEn, cats]),
        ([ky, hed], [qz, fs, cats]),
        ([ky, oDi], [qz, mgts, gs]),
        ([ky, oDi], [qz, cEn, cats]),
        ([ky, oDi], [qz, cats, pyp]),
        ([ky, oDi], [qz, cats, mgsp]),
        ([ky, oDi], [qz, gs, mgsp]),
        ([ky, oDi], [qz, gs, fo]),
        ([ky, di], [qz, mgts, gs]),
        ([ky, di], [qz, cEn, cats]),
        ([ky, di], [qz, cats, pyp]),
        ([ky, di], [qz, cats, mgsp]),
        ([ky, di], [qz, gs, mgsp]),
        ([ky, di], [qz, gs, fo]),
        ([ky, hed], [qz, cats, alm]),
        ([ky, hed], [qz, cats, herc]),
        ([ky, hed], [qz, gs, herc]),
        ([ky, hed], [qz, gs, fa]),
        ([an, oEn], [qz, oDi, mgts]),
        ([an, oEn], [qz, oDi, pyp]),
        ([an, oDi], [qz, oEn, gs]),
        ([an, oEn], [qz, oDi, mgsp]),
        ([an, oEn], [qz, mgts, di]),
        ([an, oEn], [qz, mgts, gs]),
        ([an, oEn], [qz, di, pyp]),
        ([an, di], [qz, oEn, gs]),
        ([an, oEn], [qz, di, mgsp]),
        ([an, hed], [qz, fs, gs]),
        ([an, fs], [qz, hed, alm]),
        ([an, fs], [qz, hed, herc]),
        ([an, cEn], [qz, oDi, mgts]),
        ([an, pyp], [qz, oDi, mgts]),
        ([an, cEn], [qz, oDi, pyp]),
        ([an, oDi], [qz, cEn, gs]),
        ([an, cEn], [qz, oDi, mgsp]),
        ([an, pyp], [qz, oDi, mgsp]),
        ([oDi, pyp], [qz, an, fo]),
        ([an, oDi], [qz, gs, mgsp]),
        ([an, fo], [qz, oDi, mgsp]),
        ([an, cEn], [qz, mgts, di]),
        ([an, pyp], [qz, mgts, di]),
        ([an, cEn], [qz, mgts, gs]),
        ([an, pyp], [qz, mgts, gs]),
        ([an, cEn], [qz, di, pyp]),
        ([an, di], [qz, cEn, gs]),
        ([an, cEn], [qz, di, mgsp]),
        ([an, pyp], [qz, di, mgsp]), 
        ([di, pyp], [qz, an, fo]), 
        ([an, di], [qz, gs, mgsp]),
        ([an, fo], [qz, di, mgsp]),
        ([an, hed], [qz, gs, herc]),
        ([an, alm], [qz, hed, herc]),
        ([hed, alm], [qz, an, fa]),
        ([an, fa], [qz, hed, herc]),
        # ([oEn, fs], [qz, fo, fa]), # underdetermined
        ([oEn, cats], [qz, oDi, mgsp]),
        ([oEn, gs], [qz, oDi, mgsp]),
        ([mgts, alm], [qz, oEn, herc]),
        ([oEn, cats], [qz, di, mgsp]),
        ([oEn, gs], [qz, di, mgsp]),
        ([oEn, alm], [qz, pyp, fa]), 
        ([alm, mgsp], [qz, oEn, herc]),
        ([fs, cats], [qz, hed, herc]),
        ([fs, gs], [qz, hed, herc]),
        ([fs, pyp], [qz, alm, fo]),
        ([pyp, herc], [qz, fs, mgsp]),
        ([mgts, hed], [qz, oDi, herc]),
        ([oDi, mgts], [qz, cats, fo]),
        ([cEn, cats], [qz, oDi, mgsp]),
        ([cEn, gs], [qz, oDi, mgsp]),
        ([oDi, cats], [qz, gs, mgsp]),
        ([oDi, cats], [qz, gs, fo]),
        ([oDi, pyp], [qz, gs, fo]),
        ([oDi, mgsp], [qz, gs, fo]),
        ([mgts, hed], [qz, di, herc]),
        ([mgts, di], [qz, cats, fo]),
        # ([mgts, pyp], [qz, cEn, mgsp]), ### underdetermined
        ([mgts, alm], [qz, cEn, herc]),
        ([mgts, gs], [qz, cats, fo]),
        ([mgts, alm], [qz, pyp, herc]),
        ([mgts, fa], [qz, pyp, herc]),
        ([cEn, cats], [qz, di, mgsp]),
        ([cEn, gs], [qz, di, mgsp]),
        ([di, cats], [qz, gs, mgsp]),
        ([di, cats], [qz, gs, fo]),
        ([di, pyp], [qz, gs, fo]),
        ([di, mgsp], [qz, gs, fo]),
        ([hed, cats], [qz, gs, herc]),
        ([hed, cats], [qz, gs, fa]),
        ([hed, alm], [qz, gs, fa]),
        ([hed, herc], [qz, gs, fa]),
        ([cEn, alm], [qz, pyp, fa]),
        ([alm, mgsp], [qz, cEn, herc]),
        ([cats, pyp], [qz, gs, mgsp]),
        ([cats, alm], [qz, gs, herc]),
        ([cats, fo], [qz, gs, mgsp]),
        ([cats, fa], [qz, gs, herc]),
        ([an, jd], [ky, ab, gs]),
        ([an, mgts], [ky, oEn, cats]),
        ([an, mgts], [ky, oEn, gs]),
        ([an, pyp], [ky, oEn, cats]),
        ([an, mgsp], [ky, oEn, cats]),
        ([an, pyp], [ky, oEn, gs]),
        ([an, fo], [ky, oEn, gs]),
        ([an, alm], [ky, fs, cats]),
        ([an, herc], [ky, fs, cats]),
        ([an, alm], [ky, fs, gs]),
        ([an, fa], [ky, fs, gs]),
        ([an, mgts], [ky, oDi, gs]),
        ([an, pyp], [ky, oDi, gs]),
        ([an, pyp], [ky, oDi, fo]),
        ([an, mgts], [ky, di, gs]),
        ([an, mgts], [ky, cEn, cats]),
        ([an, mgts], [ky, cEn, gs]),
        ([an, mgsp], [ky, mgts, gs]),
        ([an, pyp], [ky, di, gs]),
        ([an, pyp], [ky, di, fo]),
        ([an, alm], [ky, hed, gs]),
        ([an, alm], [ky, hed, fa]),
        ([an, pyp], [ky, cEn, cats]),
        ([an, mgsp], [ky, cEn, cats]),
        ([an, pyp], [ky, cEn, gs]),
        ([an, fo], [ky, cEn, gs]),
        ([an, mgsp], [ky, cats, pyp]),
        ([an, herc], [ky, cats, alm]),
        ([ab, mgts], [ky, oEn, jd]),
        ([ab, pyp], [ky, oEn, jd]),
        ([ab, mgsp], [ky, oEn, jd]),
        ([ab, alm], [ky, fs, jd]),
        ([ab, herc], [ky, fs, jd]),
        ([ab, mgts], [ky, cEn, jd]),
        ([ab, pyp], [ky, cEn, jd]),
        ([ab, mgsp], [ky, cEn, jd]),
        ([ab, mgsp], [ky, jd, pyp]),
        ([ab, herc], [ky, jd, alm]),
        ([fs, mgts], [ky, oEn, herc]),
        ([fs, mgts], [ky, oEn, fa]),
        ([fs, pyp], [ky, oEn, fa]),
        ([oEn, alm], [ky, fs, fo]),
        ([fs, mgsp], [ky, oEn, fa]),
        ([oEn, herc], [ky, fs, fo]),
        ([oEn, cats], [ky, oDi, mgsp]),
        ([oEn, cats], [ky, oDi, fo]),
        ([oEn, gs], [ky, oDi, fo]),
        ([mgts, fa], [ky, oEn, herc]),
        ([oEn, cats], [ky, di, mgsp]),
        ([oEn, cats], [ky, di, fo]),
        ([oEn, gs], [ky, di, fo]),
        ([oEn, cats], [ky, gs, mgsp]),
        ([pyp, alm], [ky, oEn, herc]),
        ([pyp, fa], [ky, oEn, herc]),
        ([alm, mgsp], [ky, oEn, herc]),
        ([oEn, herc], [ky, alm, fo]),
        ([fs, mgts], [ky, cEn, herc]),
        ([fs, mgts], [ky, cEn, fa]),
        ([fs, mgts], [ky, pyp, herc]),
        ([mgts, alm], [ky, fs, mgsp]),
        ([fs, mgts], [ky, alm, fo]),
        ([mgts, herc], [ky, fs, mgsp]),
        ([fs, mgts], [ky, herc, fo]),
        ([fs, cats], [ky, hed, herc]),
        ([fs, cats], [ky, hed, fa]),
        ([fs, gs], [ky, hed, fa]),
        ([fs, pyp], [ky, cEn, fa]),
        ([cEn, alm], [ky, fs, fo]),
        ([fs, mgsp], [ky, cEn, fa]),
        ([cEn, herc], [ky, fs, fo]),
        ([fs, cats], [ky, gs, herc]),
        ([pyp, alm], [ky, fs, mgsp]),
        ([pyp, herc], [ky, fs, mgsp]),
        ([fs, mgsp], [ky, pyp, fa]),
        ([alm, fo], [ky, fs, mgsp]),
        ([cEn, cats], [ky, oDi, mgsp]),
        ([cEn, cats], [ky, oDi, fo]),
        ([cEn, gs], [ky, oDi, fo]),
        ([oDi, cats], [ky, gs, fo]),
        ([mgts, fa], [ky, cEn, herc]),
        ([mgts, alm], [ky, pyp, fa]),
        ([mgts, herc], [ky, alm, mgsp]),
        ([mgts, fa], [ky, herc, fo]),
        ([cEn, cats], [ky, di, mgsp]),
        ([cEn, cats], [ky, di, fo]),
        ([cEn, gs], [ky, di, fo]),
        ([di, cats], [ky, gs, fo]),
        ([hed, cats], [ky, gs, fa]),
        ([cEn, cats], [ky, gs, mgsp]),
        ([pyp, alm], [ky, cEn, herc]),
        ([pyp, fa], [ky, cEn, herc]),
        ([alm, mgsp], [ky, cEn, herc]),
        ([cEn, herc], [ky, alm, fo]),
        ([cats, pyp], [ky, gs, fo]),
        ([cats, alm], [ky, gs, fa]),
        ([pyp, herc], [ky, mgsp, fa]),
        ([alm, mgsp], [ky, herc, fo]),
        ([oDi, mgts], [an, oEn, mgsp]),
        ([oEn, cats], [an, oDi, mgsp]),
        ([oDi, pyp], [an, oEn, mgsp]),
        ([oDi, pyp], [an, oEn, fo]),
        ([oEn, oDi, mgsp], [an, fo]),
        ([mgts, di], [an, oEn, mgsp]),
        ([mgts, hed], [an, oEn, herc]),
        ([oEn, cats], [an, di, mgsp]),
        ([di, pyp], [an, oEn, mgsp]),
        ([di, pyp], [an, oEn, fo]),
        ([oEn, di, mgsp], [an, fo]),
        ([hed, pyp], [an, oEn, herc]),
        ([cats, pyp], [an, oEn, mgsp]),
        ([oEn, cats], [an, gs, mgsp]),
        ([oEn, gs, mgsp], [an, fo]),
        ([oDi, alm], [an, fs, mgsp]),
        ([di, alm], [an, fs, mgsp]),
        ([fs, cats], [an, hed, herc]),
        ([hed, alm], [an, fs, herc]),
        ([hed, alm], [an, fs, fa]),
        ([fs, hed, herc], [an, fa]),
        ([fs, cats], [an, gs, herc]),
        ([cats, alm], [an, fs, herc]),
        ([fs, gs, herc], [an, fa]),
        ([mgts, hed], [an, oDi, fa]),
        ([oDi, mgts], [an, cEn, mgsp]),
        ([cEn, cats], [an, oDi, mgsp]),
        ([oDi, pyp], [an, cEn, mgsp]),
        ([oDi, pyp], [an, cEn, fo]),
        ([oDi, cEn, mgsp], [an, fo]),
        ([pyp, gs], [an, oDi, mgsp]),
        ([mgts, hed], [an, di, fa]),
        ([mgts, di], [an, cEn, mgsp]),
        ([mgts, hed], [an, cEn, herc]),
        ([cats, pyp], [an, mgts, fo]),
        ([cEn, cats], [an, di, mgsp]),
        ([di, pyp], [an, cEn, mgsp]),
        ([di, pyp], [an, cEn, fo]),
        ([di, cEn, mgsp], [an, fo]),
        ([pyp, gs], [an, di, mgsp]),
        ([hed, pyp], [an, cEn, herc]),
        ([gs, alm], [an, hed, herc]),
        ([cats, pyp], [an, cEn, mgsp]),
        ([cEn, cats], [an, gs, mgsp]),
        ([cEn, gs, mgsp], [an, fo]),
        ([cats, fo], [an, gs, mgsp]),
        ([cats, fa], [an, gs, herc]),
        ([jd, pyp], [ab, oEn, mgsp]),
        ([jd, alm], [ab, fs, herc]),
        ([jd, pyp], [ab, mgts, fo]),
        ([jd, pyp], [ab, cEn, mgsp]),
        ([oDi, alm], [oEn, fs, gs]),
        ([di, alm], [oEn, fs, gs]),
        ([hed, pyp], [oEn, fs, gs]),
        ([pyp, fa], [oEn, fs, mgsp]),
        ([alm, fo], [oEn, fs, herc]),
        ([oDi, alm], [oEn, mgts, hed]),
        ([di, alm], [oEn, mgts, hed]),
        ([mgts, hed], [oEn, gs, alm]),
        ([alm, mgsp], [oEn, mgts, herc]),
        ([mgts, fa], [oEn, alm, mgsp]),
        ([alm, fo], [oEn, mgts, fa]),
        ([mgts, mgsp, fa], [oEn, herc]),
        ([hed, pyp], [oEn, gs, alm]),
        ([pyp, fa], [oEn, alm, mgsp]),
        ([pyp, fo, fa], [oEn, herc]),
        ([alm, fo], [oEn, mgsp, fa]),
        ([mgts, hed], [fs, oDi, cats]),
        ([mgts, hed], [fs, oDi, gs]),
        ([oDi, alm], [fs, mgts, hed]),
        ([oDi, alm], [fs, mgts, cats]),
        ([oDi, alm], [fs, cEn, gs]),
        ([oDi, alm], [fs, pyp, gs]),
        ([mgts, hed], [fs, di, cats]),
        ([mgts, hed], [fs, di, gs]),
        ([di, alm], [fs, mgts, hed]),
        ([di, alm], [fs, mgts, cats]),
        ([pyp, fa], [fs, mgts, fo]),
        ([alm, mgsp], [fs, mgts, herc]),
        ([alm, fo], [fs, mgts, mgsp]),
        ([mgts, herc, fo], [fs, mgsp]),
        ([di, alm], [fs, cEn, gs]),
        ([di, alm], [fs, pyp, gs]),
        ([hed, pyp], [fs, cEn, gs]),
        ([pyp, fa], [fs, cEn, mgsp]),
        ([alm, fo], [fs, cEn, herc]),
        ([alm, fo], [fs, pyp, herc]),
        ([pyp, fa], [fs, herc, fo]),
        ([alm, fo, fa], [fs, mgsp]),
        ([mgts, hed, cEn], [oDi, alm]),
        ([hed, mgsp], [oDi, cats, fa]),
        ([hed, cats, fo], [oDi, herc]),
        ([cats, mgsp, fa], [oDi, herc]),
        ([di, alm], [mgts, hed, cEn]),
        ([cEn, gs, alm], [mgts, hed]),
        ([pyp, gs, alm], [mgts, hed]),
        ([alm, mgsp], [mgts, cEn, herc]),
        ([cEn, alm, mgsp], [mgts, fa]),
        ([alm, fo], [mgts, cEn, fa]),
        ([cEn, herc], [mgts, mgsp, fa]),
        ([pyp, herc], [mgts, fo, fa]),
        ([hed, mgsp], [di, cats, fa]),
        ([hed, cats, fo], [di, herc]),
        ([cats, mgsp, fa], [di, herc]),
        ([cEn, gs, alm], [hed, pyp]),
        ([cats, herc, fo], [hed, mgsp]),
        ([pyp, fa], [cEn, alm, mgsp]),
        ([pyp, fo, fa], [cEn, herc]),
        ([alm, fo], [cEn, mgsp, fa]),
    ]
    
    generate_reaction(outdir,version, 'eclogitization_2024', phases, reactions_2024)
    generate_reaction(outdir,version, 'abdullaziz', phases_mafic, reactions_abdullaziz)
    generate_reaction(outdir,version, 'claude', phases_mafic, reactions_claude)

def generate_reaction(outdir, version, name, phases, reactions):
    
    dbfile = os.path.join(os.path.pardir, 'database', 'tcg_{}_database.tar.gz'.format(version))
    dbpath = 'file://{}'.format(dbfile)
    rx_suffix = '_{}_rx'.format(version)
    phase_suffix = '_{}_ph'.format(version)
    em_suffix = '_{}_em'.format(version)

    try:
        os.mkdir(outdir)
    except FileExistsError:
        pass

    name = name+rx_suffix
    phases = [ph+phase_suffix for ph in phases]
    rxn = SLBReactions(name, len(reactions), phases, dbpath, reference)
    for reaction in reactions:
        reactants = [[[ph+phase_suffix, em+em_suffix]
                      for ph, em in reaction[i]] for i in range(2)]
        rxn.add_reaction(*reactants)
    rxn.tofile(outdir)


if __name__ == '__main__':
    import argparse
    import os

    parser = argparse.ArgumentParser(\
        description="""Generate eclogitization rxml for a specified thermodynamic database (slb or slb21).""")
    parser.add_argument('-o', '--outdir', action='store', metavar='outdir',
                        default=os.path.join(os.path.pardir, 'database', 'reactions'), type=str, required=False,
                        help='Output directory for rxml files (defaults to ../database/reactions relative to script).')
    parser.add_argument('-v', '--version', action='store', metavar='version', default='slb', type=str, required=False,
                        help='SLB database version as "slb" (default) or "slb21".')
    args = parser.parse_args()
    print(args.outdir)
    generate_reactions(args.outdir, args.version)
